#!/usr/bin/env sh

source lib/keepass.sh

action=REBUILD
show_trace=
command=test
cleanup=0
while getopts 'hdsyurbctm' OPTION; do
  case "$OPTION" in
    h)
      echo "Usage: $0 [-hdsur] [version/machine] [module]"
      echo "  -h                   this help"
      echo "  -d                   run nix-collect-garbage"
      echo "  -s                   rebuild & switch"
      echo "  -y                   dry run"
      echo "  -u                   upgrade channel and switch"
      echo "  -b                   rebuild & boot"
      echo "  -r <version>         release - rebuild & switch, git tag and label with <version> e.g. $0 -r v1"
      echo "  -m [machine]         Build a different machine from the running one. e.g. sirius/aramid/spruce/sapling"
      echo "  -c                   Diff of changes between latest & prev upgrade"
      echo "  -t                   Show trace"
      echo "  [module]             Pick an alternative base module from machines/$machine/. Defaults to default.nix"
      exit 0
      ;;
    d)
      cleanup=1
      ;;
    s)
      action=SWITCH
      command=switch
      ;;
    y)
      command=dry-build
      ;;
    b)
      action=BOOT
      command=boot
      ;;
    u)
      action=UPGRADE
      command=switch
      ;;
    c)
      nvd diff $(ls -d1v /nix/var/nix/profiles/system-*-link|tail -n 2)
      exit 0
      ;;
    t)
      show_trace=--show-trace
      ;;
    m)
      command=build
      machine=GET
      ;;
    r)
      action=RELEASE
      command=switch
      shift $(($OPTIND - 1))
      version="$1"

      if [ -z "$version" ]; then
        echo "Missing version from $0 -r <version>"
        exit 1
      else
        git tag "$version"
      fi

      ;;
  esac
done
shift $(($OPTIND - 1))

if [ "$machine" = "GET" ]; then
  machine=$1
  shift
else
  machine=$(hostname)
  commit_msg=$1
fi

module=$1

configuration_nix=src/machines/$machine/$module

# Check we have Internet
if ! ping -c 1 google.com > /dev/null 2>&1; then
  # Check we have Wifi credentials
  if [ -f "secrets/wifi" ]; then
    source secrets/wifi
  else
    [ -f "secrets/password" ] && passwd=$(cat "secrets/password")
    askpass "Enter KeePass password for wifi credentials:"
    keepass_fetch_wifi
  fi

  echo "[WIFI] Network name (SSID) [$ssid]:"
  read ssid_override
  if [ "$ssid_override" ]; then
    echo "[WIFI] Password (PSK):"
    ssid=ssid_override
    read psk
  fi

  # Add to NetworkManager if not
  nmcli device wifi connect $ssid password $psk
  echo "[WIFI] Connecting..."
  while ! ping -c 1 google.com > /dev/null 2>&1; do sleep 1; done
fi

[ "$version" ] && echo "[LABEL] $version"

# Check if both catppuccin and nixos-hardware channels have been added
if ! sudo nix-channel --list | tr '\n' ' ' | grep -sE 'catppuccin.*nixos-hardware' > /dev/null; then
  sudo nix-channel --add https://github.com/catppuccin/nix/archive/main.tar.gz catppuccin
  sudo nix-channel --add https://github.com/NixOS/nixos-hardware/archive/master.tar.gz nixos-hardware
  action=UPGRADE
fi

# Fetch hashed_password and ssh keys unless they already exist
home=$HOME
if [ ! -f secrets/hashed_password ] || [ ! -d $home/.ssh ]; then
  askpass "Enter KeePass password for hashed_password & .ssh/:"
  keepass_export_hashed_password "secrets/hashed_password"

  # Export public/private keys for this machine to ~/.ssh/
  mkdir -p $home/.ssh
  chmod 700 $home/.ssh
  keepass_export_keys $prefix $machine
  keepass_export_keys $prefix $machine github
  keepass_export_keys $prefix $machine gitlab
fi

# Export all public keys to secrets/ for use in src/ssh.nix
for m in spruce sirius aramid sapling; do
  if [ ! -f secrets/${prefix}_${m}.pub ]; then
    askpass "Enter KeePass password for public key export:"
    keepass_export_key public ${prefix}_${m} secrets/
  fi
done

# Switch to key-based encryption on drive 2 of machines with 2 drives
# Currently, this is just Minoo
pool_name="dpool"
zfs_keydir="/root"
zfs_keypath="$zfs_keydir/.$pool_name.key"
if [ "$machine" = "minoo" ] && [ ! -f "$zfs_keypath" ]; then
  source lib/disks.sh
  SUDO "mkdir -p $zfs_keydir"
  SUDO "chmod 700 $zfs_keydir"
  generate_key $zfs_keypath
  change_key $pool_name $zfs_keypath
fi

echo "[$action] $machine"
[ "$cleanup" = "1" ] && sudo nix-collect-garbage -d
[ "$action" = "UPGRADE" ] && sudo nix-channel --update
[ "$version" ] && label="NIXOS_LABEL=$version"
sudo $label NIXOS_CONFIG=$(pwd)/$configuration_nix nixos-rebuild $command $show_trace
#                                                           -I nixpkgs=/data/code/nixpkgs # -------^

# Remove secrets once we're done encrypting drives and accessing KeePass
if [ "$?" -eq "0" ]; then
  [ -f secrets/wifi ] && sudo rm secrets/wifi
  [ -f secrets/password ] && sudo rm secrets/password
fi