#!/usr/bin/env sh

echo "0000:01:00.0" > /sys/bus/pci/devices/0000:01:00.0/driver/unbind
echo "0000:01:00.1" > /sys/bus/pci/devices/0000:01:00.1/driver/unbind

# Rebind to NVIDIA
modprobe nvidia
echo "0000:01:00.0" > /sys/bus/pci/drivers/nvidia/bind
echo "0000:01:00.1" > /sys/bus/pci/drivers/snd_hda_intel/bind