#!/usr/bin/env sh

source ./gpu_ids.ini

echo "Unbinding GPU from the host..."
sleep 1

sudo sh -c 'echo "0000:01:00.0" > /sys/bus/pci/drivers/nouveau/unbind'
sudo sh -c 'echo "0000:01:00.1" > /sys/bus/pci/drivers/nouveau/unbind'

echo "Binding GPU to VFIO..."
sudo modprobe vfio-pci

echo "Hand over GPU to vfio-pci"

# Replace 10de 1b80 and 10de 10f0 with your actual vendor:device IDs if different.
sudo sh -c "echo '${vendor} ${gpu_id}' > /sys/bus/pci/drivers/vfio-pci/new_id"
sudo sh -c "echo '${vendor} ${audio_id}' > /sys/bus/pci/drivers/vfio-pci/new_id"

echo "GPU is now assigned to VFIO."