#!/usr/bin/env sh

source lib/keepass.sh

askpass "KeePass password"

echo "Hetzner"
echo "Spruce: $(keepass_export_key "public" "${prefix}_spruce_hetzner")"

echo "Local"
echo "Aramid: $(keepass_export_key "public" "${prefix}_aramid")"
echo "Minoo: $(keepass_export_key "public" "${prefix}_minoo")"
echo "Minoo: $(keepass_export_key "public" "id_ecdsa_minoo")"
echo "Sapling: $(keepass_export_key "public" "${prefix}_sapling")"
echo "Seedling: $(keepass_export_key "public" "${prefix}_seedling")"
echo "Spruce: $(keepass_export_key "public" "${prefix}_spruce")"
echo "Suuno: $(keepass_export_key "public" "${prefix}_suuno")"
echo ""

echo "GitHub"
echo "Aramid: $(keepass_export_key "public" "${prefix}_aramid_github")"
echo "Minoo: $(keepass_export_key "public" "${prefix}_minoo_github")"
echo "Sapling: $(keepass_export_key "public" "${prefix}_sapling_github")"
echo "Seedling: $(keepass_export_key "public" "${prefix}_seedling_github")"
echo "Spruce: $(keepass_export_key "public" "${prefix}_spruce_github")"
echo ""

echo "GitLab"
echo "Aramid: $(keepass_export_key "public" "${prefix}_aramid_gitlab")"
echo "Minoo: $(keepass_export_key "public" "${prefix}_minoo_gitlab")"
echo "Sapling: $(keepass_export_key "public" "${prefix}_sapling_gitlab")"
echo "Seedling: $(keepass_export_key "public" "${prefix}_seedling_gitlab")"
echo "Spruce: $(keepass_export_key "public" "${prefix}_spruce_gitlab")"