#!/usr/bin/env sh

source lib/commands.sh
source lib/disks.sh
source lib/keepass.sh
source lib/run.sh
source lib/steps.sh
source config/aramid.sh
source config/minoo.sh
source config/sapling.sh
source config/spruce.sh

run "$@"