#!/usr/bin/env sh
[ ! -d tmp/emulated_tpm ] && mkdir -p tmp/emulated_tpm

sudo swtpm socket --tpmstate dir=tmp/emulated_tpm \
  --ctrl type=unixio,path=tmp/emulated_tpm/swtpm-sock \
  --log level=20 --tpm2