#!/usr/bin/env sh

device=$1
interface=$2
vendor=$(cat /sys/bus/pci/devices/$device/vendor)
product=$(cat /sys/bus/pci/devices/$device/device)

if [ -z "$interface" ]; then
  echo "Usage: $0 <device> <interface>"
  echo "  device - bus device e.g. 0000:01:00.0"
  echo "  interface - xhci_hcd | nvme | ahci"
  exit 1
fi

# Unbind from previous interface
if [ -e /sys/bus/pci/devices/$device/driver ]; then
  echo "${device}" > /sys/bus/pci/devices/${device}/driver/unbind
fi

# bind (with create) to new interface
echo "$vendor $product" > /sys/bus/pci/drivers/$interface/new_id 2> /dev/null
if [ "$?" = "1" ]; then
  echo "${device}" > /sys/bus/pci/drivers/$interface/bind
fi