#!/usr/bin/env sh

[ ! -f tmp/nixos.qcow2 ] && qemu-img create -f qcow2 tmp/nixos.qcow2 256G

qemu-system-x86_64-uefi \
  -machine vmport=off \
  -cpu host \
  -vga virtio \
  -display sdl,gl=on \
  -enable-kvm \
  -m 10G \
  -nic user,model=virtio \
  -drive file=tmp/nixos.qcow2,if=none,id=nvm \
  -device nvme,serial=deadbeef,drive=nvm \
  -full-screen
  #-cdrom result/iso/*.iso