#!/usr/bin/env sh

# https://wiki.debian.org/SecureBoot/VirtualMachine
# https://macroform-node.medium.com/building-a-windows-11-vm-with-qemu-using-tpm-emulation-for-research-malware-analysis-part-1-8846378b9582
# https://ubuntu.com/server/docs/gpu-virtualization-with-qemu-kvm - Suggestion for -device for GPU passthrough settings
# Turn off Windows Fast Start: HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\Power -> HiberbootEnabled -> 0
# lsblk -o NAME,LABEL,MODEL,SERIAL
# lshw -short # Nice list of all devices and peripherals
# sudo lshw -businfo # Devices and connected bus (e.g. 0000:04:00.0)

#
# TODO:
# [x] - Try to get USB Audio controller working
# [x] - ~Try again to get cset shield to work with taskset~ - cgroups v2 is not supported in cset
# [ ] - Which NIC card to use? Or should I use bridge networking? What's the advantage?
# [ ] Add -d to swtpm - Not sure this is working properly - Windows is reporting an error with TPM

tpm_dir=/data/code/nixfiles/tmp/emulated_tpm
tpm_sock=${tpm_dir}/swtpm-sock
OVMF_DIR=/nix/store/my571d8qw91lxnhsk439z8sj233c2cz7-OVMF-202411-fd/FV
OVMF_CODE=${OVMF_DIR}/OVMF_CODE.fd
OVMF_VARS=OVMF_VARS.ms.fd
SSH_PORT="5555"

GPU="01:00.0"
GPU_AUDIO="01:00.1"
USB_CONTROLLER="0000:07:00.0"
GAMES_SSD="0000:08:00.0"

# Bind PCI devices
./vfio bind $USB_CONTROLLER
./vfio bind $GAMES_SSD

if [ ! -f tmp/$OVMF_VARS ]; then
  cp $OVMF_DIR/$OVMF_VARS tmp/$OVMF_VARS
  chmod +w tmp/$OVMF_VARS
fi

[ ! -f tmp/windows.qcow2 ] && qemu-img create -f qcow2 tmp/windows.qcow2 128G

rm -rf $tpm_dir
[ ! -d $tpm_dir ] && mkdir -p $tpm_dir


swtpm socket --tpmstate dir=${tpm_dir} --ctrl type=unixio,path=${tpm_sock} --log level=20 --tpm2 -d
swtpm_pid=$!

# Unbind USB Controller and bind to VFIO
#echo "0000:${USB_CONTROLLER}" | tee /sys/bus/pci/devices/0000:${USB_CONTROLLER}/driver/unbind
#echo "0000:${USB_CONTROLLER}" | tee /sys/bus/pci/drivers/vfio-pci/bind


# CPU Scaling
echo performance | tee /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor

# CPU Pinning
CORES=28
HOST_CORES="0,1,16,17"
VM_CORES="2-15,18-31"
RAM=24

# Hugepages
HUGEPAGES_SIZE=2
HUGEPAGES_TOTAL=$((RAM * 1024 / HUGEPAGES_SIZE))
echo "Hugepages total: ${HUGEPAGES_TOTAL}"
hugeadm --pool-pages-min "${HUGEPAGES_SIZE}MB:${HUGEPAGES_TOTAL}"
hugeadm --set-recommended-shmmax
mkdir -p /dev/hugepages
mount -t hugetlbfs nodev /dev/hugepages

# https://www.qemu.org/docs/master/system/i386/hyperv.html
HV_ENLIGHT="hv_relaxed,hv_vapic,hv-vpindex,hv-runtime,hv-time,hv-synic,hv-stimer,hv-tlbflush,hv-frequencies,hv-apicv"

read -p "Start VM? (y/n): " answer
if [[ "$answer" =~ ^[Yy]$ ]]; then

taskset -c $VM_CORES qemu-system-x86_64 \
  -name "Windows 11 on Qemu",process=win11vm \
  -machine q35,smm=on,usb=off,accel=kvm \
  -enable-kvm \
  -vga none \
  -nographic \
  -serial none \
  -parallel none \
  -smp $CORES,cores=$(($CORES / 2)),threads=2,sockets=1 \
  -cpu host,kvm=off,${HV_ENLIGHT},hv_spinlocks=0x1fff,hv_vendor_id=0xDEADBEEFFF \
  -m ${RAM}G \
  -mem-prealloc \
  -mem-path /dev/hugepages \
  -drive file=tmp/windows.qcow2,if=none,id=win \
  -chardev socket,id=chrtpm,path=${tpm_sock} \
  -tpmdev emulator,id=tpm0,chardev=chrtpm \
  -device vfio-pci,host=$GPU,multifunction=on,x-vga=on \
  -device vfio-pci,host=$GPU_AUDIO \
  -device vfio-pci,host=$USB_CONTROLLER \
  -device vfio-pci,host=$GAMES_SSD \
  -device qemu-xhci \
  -device usb-host,vendorid=0x320f,productid=0x504a \
  -device usb-host,vendorid=0x258a,productid=0x2022 \
  -device usb-host,vendorid=0x258a,productid=0x2011 \
  -device usb-host,vendorid=0x28de,productid=0x2102 \
  -device usb-host,vendorid=0x28de,productid=0x2300 \
  -device usb-host,vendorid=0x0483,productid=0x0522 \
  -device usb-host,vendorid=0x0483,productid=0x0525 \
  -device usb-host,vendorid=0x22e8,productid=0xdac2 \
  -device usb-host,vendorid=0x8087,productid=0x0033 \
  -device nvme,serial=deadbeef,drive=win,bootindex=1 \
  -device tpm-tis,tpmdev=tpm0 \
  -nic user,ipv6=off,model=rtl8139,mac=84:1b:76:c9:01:a5 \
  -global driver=cfi.pflash01,property=secure,value=on \
  -drive if=pflash,format=raw,unit=0,file="${OVMF_CODE}",readonly=on \
  -drive if=pflash,format=raw,unit=1,file="tmp/${OVMF_VARS}" \
  -rtc clock=host,base=localtime,driftfix=slew

  #-object memory-backend-file,id=mem1,share=on,mem-path=/dev/hugepages,prealloc=yes,size=${RAM}G \
  #-numa node,cpus=0-27,memdev=mem1 \
  #-object memory-backend-file,id=mem1,share=on,mem-path=/dev/hugepages,prealloc=yes,size="${RAM}G" \
  #-numa node,cpus=0-27,memdev=mem1 \

  # -device usb-host,vendorid=0x046d,productid=0x0825 \
  # -smp cpus=28,cores=14,threads=2,sockets=1 \
  # -cdrom tmp/virtio-win-0.1.266.iso \
  #-cdrom /data/downloads/windows_11_ltsc.iso \
  #-device intel-hda -device hda-duplex \
  #-net nic,model=virtio -net user,hostfwd=tcp::${SSH_PORT}-:22 \

{ kill $swtpm_pid && wait $swtpm_pid; } 2>/dev/null

fi

umount /dev/hugepages
hugeadm --pool-pages-min "${HUGEPAGES_SIZE}MB:0"

# Unbind PCI devices
./vfio unbind $USB_CONTROLLER
./vfio unbind $GAMES_SSD

# CPU Scaling
echo powersave | tee /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor

#echo "0000:${USB_CONTROLLER}" > /sys/bus/pci/devices/0000:${USB_CONTROLLER}/driver/unbind
#echo "0000:${USB_CONTROLLER}" > /sys/bus/pci/drivers/xhci_hcd/bind